### ISSUE TITLE
Suggest topics for 25th April 2024 (Thursday)

### ISSUE THREAD

**Issue by evanlinjin** [TaiwanBitdevs/TaiwanBitdevs.github.io#29]
```
Date: 25/04/2024
Time: 19:00 - 22:00
```

# Announcement

TODO

**Comment by nickfarrow** [comment]
Blake3 transaction using complex script (BitVM)

https://twitter.com/robin_linus/status/1776152948927574210

**Comment by nickfarrow** [comment]
Samourai Wallet Founders Arrested & Charged with Money Laundering, Unlicensed Money Transmitting Offenses
https://www.justice.gov/usao-sdny/pr/founders-and-ceo-cryptocurrency-mixing-service-arrested-and-charged-money-laundering

**Comment by nickfarrow** [comment]
ViaBTC Pool Bug Disclosure, rewarded with relatively tiny bounty
https://b10c.me/blog/012-viabtc-spv-vulnerability-disclosure/

**Comment by nickfarrow** [comment]
Unpatchable vulnerability in Apple chips leaks keys
https://gofetch.fail/

**Comment by nickfarrow** [comment]
Phoenixd Server
https://twitter.com/PhoenixWallet/status/1771236080680841668

**Comment by nickfarrow** [comment]
xz-utils backdoor would've allowed remote access to almost every linux machine
https://twitter.com/niftynei/status/1774055520246137306

**Comment by nickfarrow** [comment]
Ledger Installer - Setup Ledger without Ledger Live
https://github.com/darosior/ledger_installer

**Comment by nickfarrow** [comment]
Mining Pool and Custody Centralization
https://twitter.com/0xB10C/status/1780611768081121700

**Comment by nickfarrow** [comment]
OXT dot me server is down
https://oxt.me
